title: "Skander Kacem"
#tagline: ""
description: "Thinking out loud"
baseurl: ""
url: ""
email: skanderkacem@gmail.com
# twitter_username: SkanderKacem
github_username:  skacem
# linkedin_link: http://linkedin.com/in/skander-kacem
stackoverflow: 
gscholar: 
researchgate: Skander-Kacem
timezone: Europe/Berlin

# Giscus comments (uses GitHub Discussions)
giscus:
  repo: "skacem/skacem.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnkzNzY5MjgzNDU="
  category: "General"
  category_id: "DIC_kwDOFnd4Wc4Cwv4F"

markdown: kramdown
permalink: pretty

kramdown:
  math_engine: mathjax
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

# Build settings
markdown: kramdown
#permalink: pretty

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

emoji:
  src: "https://github.githubassets.com/images/icons/"

# Pagination Settings
pagination:
  enabled: false
  debug: true
  collection: 'posts'
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page
  per_page: 8
  offset: 0
  permalink: '/blog/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
